export const DUTCH_JSON: any = {
    USER_NAME_PLACEHOLDER: 'Voer naam in',
    JOIN_NOW: 'Deelnemen',
    GO_LIVE: 'Ga live',
    GET_STARTED: "Aan de slag!",
    GET_STARTED_SUB_TITLE: "Stel je microfoon en camera in voordat je deelneemt",
    FIRST_TO_JOIN: "Je bent de eerste die deelneemt",
    OTHER: "andere",
    IN_THE_SESSION: "andere deelnemer",
    DEVICE_SETTINGS: "Apparaat instellingen",
    NOTIFICATIONS: "Notificaties",
    LAYOUT: "Weergave",
    SETTINGS: "Instellingen",
    VIDEO: "Video",
    MICROPHONE: "Microfoon",
    AUDIO: "Microfoon",
    SPEAKER: "Spreker",
    SELECT_DEVICE_FROM_LIST: "Selecteer apparaat uit de lijst",
    TEST: "Test",
    NOISE_REDUCTION_MESSAGE: "Ruisonderdrukking ingeschakeld",
    TURN: "Microfoon",
    OFF: "uit",
    ON: "aan",
    SWITCH_CAMERA: "Camera wisselen",
    SWITCH_CAMERA_ERROR: "Fout bij het omdraaien van de camera",
    PLAYING_SOUND: "Geluid afspelen...",
    PLAY_TEST_SOUND: "Speel testgeluid af",
    AUDIO_SETTINGS: "Instellingen",
    NOISE_REDUCED: "Ruis verminderd",
    REDUCE_NOISE: "Verminder ruis",
    CONFIGURE_VIRTUAL_BACKGROUND: "Achtergrond instellen",
    VIRTUAL_BACKGROUND: "Virtuele achtergrond",
    EFFECTS: "Effecten",
    NO_EFFECT: "Geen effect",
    BLUR: "Vervagen",
    HIGH: "Hoog",
    BACKGROUNDS: "Achtergronden",
    PEER_JOINED: "Deelnemer toegetreden",
    PEER_LEAVE: "Deelnemer heeft de sessie verlaten",
    HAND_RAISED: "Handen omhoog",
    ERROR: "Fout",
    TILES_IN_VIEW: "Tegels zichtbaar",
    AUDIO_ONLY_MODE: "Alleen audio-modus",
    MIRROR_LOCAL_VIDEO: "Spiegel video",
    SIT_BACK_AND_RELAX: "Even geduld totdat anderen deelnemen",
    SCREEN_SHARE_CANCEL: "Gebruiker heeft geen toestemming gekregen voor toegang tot het opnameapparaat",
    START_SHARING: "Start delen",
    CHOOSE_WHAT_YOU_WANT_TO_SHARE: "Kies wat je wilt delen",
    SHARE_SCREEN: "Scherm delen",
    SHARE_SCREEN_SUBTITLE: "Deel je tabblad, venster of je gehele scherm",
    SHARE_PDF: "Deel PDF",
    NEW: "Nieuw",
    SHARE_PDF_SUBTITLE: "Maak notities, teken figuren, en meer met PDF's",
    MORE_OPTIONS: "Meer opties",
    PARTICIPANTS: "Deelnemers",
    HAND: "Hand",
    RAISE: "Salarisverhoging",
    LOWER: "Lager",
    EMOJI_REACTIONS: "Emoji-reacties",
    POLLS_AND_QUIZZES: "peilingen en quizzen",
    BE_RIGHT_BACK: "Ben zo terug",
    RECORDING_ON: "Opnemen Aan",
    STARTING_RECORDING: "Opname starten",
    START_RECORDING: "Begin met opnemen",
    ABOUT_SESSION: "Over sessie",
    ENABLE: "Inschakelen",
    DISABLE: "Uitzetten",
    PICTURE_IN_PICTURE: "Beeld-in-beeld",
    SHOW_STATS: "Toon statistieken op vensters",
    STATS_FOR_NERDS: "Statistieken voor nerds",
    POP_OUT_CHAT: "Pop-outchat",
    FULL_SCREEN: "volledig scherm",
    EXIT_FULL_SCREEN: "Volledig scherm afsluiten",
    GO: "Gaan",
    EXIT: "Uitgang",
    SEARCH_FOR_PARTICIPANTS: "Zoek naar deelnemers",
    NO_PARTICIPANTS: "Geen deelnemers",
    NO_MATCHING_PARTICIPANTS: "Geen deelnemers gevonden",
    YOU: "Jij",
    CHAT: "Chat",
    HOST: "Gastheer",
    START_A_CONVERSATION: "Begin een gesprek",
    NO_MESSAGES_YET: "Nog geen berichten",
    NO_MESSAGES_YET_SUBTITLE: "Er zijn hier nog geen berichten. Begin een gesprek door een bericht te sturen.",
    SEND_A_MESSAGE: "Stuur een bericht",
    TO: "Naar",
    CHOOSE_PARTICIPANT: "Kies Deelnemer",
    EVERYONE: "Iedereen",
    PEER: "Peer",
    GUEST: "Gast",
    SEARCH: "Zoekopdracht",
    ROLES: "Rollen",
    PAUSE_CHAT: "Pauzeer het chatten",
    CHAT_PAUSED: "Chat onderbroken",
    CHAT_PAUSED_BY: "Chat is gepauzeerd door",
    RESUME: "Resume",
    BLOCKED_MESSAGE: "Je bent geblokkeerd voor het verzenden van berichten",
    POLL_AND_QUIZES: "Polls en quizzen",
    OPEN: "Open",
    CLOSE: "Dichtbij",
    POLL_TYPE: "Selecteer het type waarmee je verder wilt gaan",
    POLL: "peiling",
    QUIZ: "Quiz",
    HIDE_VOTE_COUNT: "Stemmen verbergen",
    ENTER_NAME: "Voer een naam in om door te gaan",
    CREATE: "aanmaken",
    NAME_THIS: "Naam",
    PREVIOUS_POLLS_AND_QUIZZES: "Eerdere peilingen en quizzen",
    VIEW: "Weergave",
    QUESTION: "Vraag",
    OF: "van",
    QUESTION_TYPE: "Vraagtype",
    OPTIONS: "Opties",
    USE_THE_RADIO_CORRECT: "Gebruik de keuzerondjes om het juiste antwoord aan te geven",
    USE_THE_CHECK_BOX_CORRECT: "Gebruik de selectievakjes om het juiste antwoord(en) aan te geven",
    ADD_AN_OPTION: "Voeg een optie toe",
    POINT_WEIGHTAGE: "Puntenaantal",
    AT_LEAST_TWO_OPTIONS: "Er moeten minimaal twee opties worden toegevoegd",
    FILL_ALL_THE_FIELDS: "Vul alle velden in",
    MARK_CORRECT_ANSWERS: "en markeer het juiste antwoord(en)",
    TO_CONTINUE: "doorgaan",
    SAVE: "Opslaan",
    DELETE_QUESTION: "Vraag verwijderen",
    QUESTION_WILL_BE_DELETED: "De vraag wordt verwijderd. Je kunt deze actie niet ongedaan maken.",
    CANCEL: "Annuleer",
    DELETE: "Verwijderen",
    ADD_ANOTHER_QUESTION: "Voeg nog een vraag toe",
    LAUNCH: "Start",
    ASK_A_QUESTION: "Stel een vraag",
    "SINGLE-CHOICE": "Enkele keuze",
    "MULTIPLE-CHOICE": "Meerkeuze",
    OPTION: "Optie",
    EDIT: "Bewerking",
    NOT_REQUIRED_TO_ANSWER: "Niet verplicht om te antwoorden",
    ANSWER: "Antwoord",
    VOTE: "Stemmen",
    STARTED_A: "begon een",
    PARTICIPANT: "Deelnemer",
    SINGLE_CHOICE: "Enkele keuze",
    MULTIPLE_CHOICE: "Meerkeuze",
    END: "Einde",
    VIEW_LEADERBOARD: "Bekijk klassement",
    ANSWERED: "Beantwoord",
    VOTED: "Gestemd",
    SKIPPED: "Overgeslagen",
    DRAFT: 'Voorlopige versie',
    LIVE: 'Live',
    ENDED: 'Beëindigd',
    VOTES: "Stemmen",
    PARTICIPATION_SUMMARY: "Overzicht",
    CORRECT_ANSWERS: "Juiste antwoorden",
    AVG_TIME_TAKEN: "Gem. Tijd genomen",
    AVG_SCORE: "Gem. Scoren",
    YOUR_RANK: "Jouw plaats",
    POINTS: "Punten",
    TIME_TAKEN: "Tijd",
    YOUR_ANSWER: "Jouw antwoord",
    RAISE_HAND: "Hand opsteken",
    LOWER_HAND: "Hand omlaag",
    EMOGI_REACTION: "Emoji reactie",
    START: "Start",
    STOP: "Stop",
    SCREEN_SHARING: "scherm delen",
    SHARE: "Deel",
    VIEW_OPTIONS: "Bekijk opties",
    OPEN_CHAT: "Open chat",
    LEAVE_ROOM: "Sessie verlaten",
    LEAVE_SESSION: "Sessie verlaten",
    LEAVE_STREAM: "Verlaat Stroom",
    LEAVE_SESSION_SUB_TITLE: "Anderen zullen doorgaan nadat je de sessie hebt verlaten. Je kunt opnieuw deelnemen aan de sessie.",
    SESSION: "sessie",
    STREAM: "stroom",
    AGAIN: "opnieuw",
    END_SESSION: "Sessie beëindigen",
    END_STREAM: "Einde stroom",
    END_SESSION_SUB_TITLE: "De sessie wordt voor iedereen beëindigd. Je kunt dit niet ongedaan maken.",
    THE: "De",
    YOU_LEFT_THE_ROOM: "Je verliet de kamer",
    HAVE_A_NICE_DAY: "Prettige dag",
    LEFT_BY_MISTAKE: "Per ongeluk achtergelaten?",
    REJOIN: "Opnieuw deelnemen",
    END_RECORDING: "Beëindig de opname",
    END_RECORDING_SUB_TITLE: "Weet je zeker dat je de opname wilt stoppen?",
    DONT_END: "Eindig niet",
    STOP_RECORDING: "Stop opname",
    STARTING: "Beginnen",
    RECORDING: "opname",
    LEAVE: "Sessie verlaten",
    OTEHRS_WILL_CONTINUE: "Anderen zullen doorgaan nadat je vertrekt. Je kunt opnieuw deelnemen aan de sessie.",
    CAMERA_ON: "Camera aan",
    CAMERA_OFF: "Camera uit",
    PIN_TILE: "Vastzetten",
    UN_PIN: "Vastzetten opheffen",
    MINIMIZE_YOUR_VIDEO: "Verklein je video",
    REQUEST_TO_UNMUTE_VIDEO: "Verzoek om camera aan te zetten",
    MUTE_VIDEO: "Camera uitzetten",
    REQUEST_TO_UNMUTE_AUDIO: "Verzoek om microfoon aan te zetten",
    MUTE_AUDIO: "Microfoon uitzetten",
    SWITCH_ROLE: "Rol wijzigen",
    REMOVE_PARTICIPANT: "Verwijder deelnemer",
    SWITCH_ROLE_OF: "Wijzig de rol van",
    CHANGE_ROLE: "Wijzig rol",
    PERMISSION_ERROR: "Geen toegang verleend om scherm te delen",
    YOU_ARE_SHARING_YOUR_SCREEN: "Je bent je scherm aan het delen",
    STOP_SCREEN_SHARE: "Stop scherm delen",
    CHOOSE_PDF_YOU_WANT_ANNOTATE: "Kies een PDF om te delen",
    CLICK_TO_UPLOAD: "Klik om te uploaden",
    SELECT_MAXIMUM_RESOLUTION: "Kies maximum resolutie",
    UNMUTE_YOUR_AUDIO: "Je microfoon aanzetten?",
    UNMUTE_YOUR_VIDEO: "Je camera aanzetten?",
    UNMUTE_YOUR_AUDIO_TEXT: "verzoekt je om je microfoon aan te zetten.",
    UNMUTE_YOUR_VIDEO_TEXT: "verzoekt je om je camera aan te zetten.",
    WAS_MUTED_BY: "werd gedempt door",
    YOUR: "Jouw",
    RAISED_HAND: "heeft hand omhoog",
    AND: "En",
    JOINED: "is toegetreden",
    LEFT: "heeft de sessie verlaten",
    CHANGE_NAME: "Naam wijzigen",
    CHANGE_NAME_SUB_TITLE: "Uw naam is zichtbaar voor andere deelnemers aan de sessie.",
    CHANGE: "Wijziging",
};