export const DUTCH_JSON: any = {
    USER_NAME_PLACEHOLDER: 'Voer naam in',
    JOIN_NOW: 'Sluit u nu aan',
    GO_LIVE: 'Ga live',
    GET_STARTED: "Aan de slag",
    GET_STARTED_SUB_TITLE: "Stel uw audio en video in voordat u lid wordt",
    FIRST_TO_JOIN: "Jij bent de eerste die meedoet",
    OTHER: "ander",
    IN_THE_SESSION: "in de sessie",
    DEVICE_SETTINGS: "Apparaatinstellingen",
    NOTIFICATIONS: "Meldingen",
    LAYOUT: "Indeling",
    SETTINGS: "Instellingen",
    VIDEO: "Video",
    MICROPHONE: "Microfoon",
    AUDIO: "Audio",
    SPEAKER: "Spreker",
    SELECT_DEVICE_FROM_LIST: "Selecteer apparaat uit de lijst",
    TEST: "Test",
    NOISE_REDUCTION_MESSAGE: "Ruisonderdrukking ingeschakeld",
    TURN: "Schakel",
    OFF: "uit",
    ON: "op",
    SWITCH_CAMERA: "Camera wisselen",
    SWITCH_CAMERA_ERROR: "Fout bij het omdraaien van de camera",
    PLAYING_SOUND: "Geluid afspelen...",
    PLAY_TEST_SOUND: "Speel testgeluid af",
    AUDIO_SETTINGS: "Audio-instellingen",
    NOISE_REDUCED: "Ruis verminderd",
    REDUCE_NOISE: "Verminder ruis",
    CONFIGURE_VIRTUAL_BACKGROUND: "Configureer virtuele achtergrond",
    VIRTUAL_BACKGROUND: "Virtuele achtergrond",
    EFFECTS: "Effecten",
    NO_EFFECT: "Geen effect",
    BLUR: "Vervagen",
    HIGH: "Hoog",
    BACKGROUNDS: "Achtergronden",
    PEER_JOINED: "Peer aangesloten",
    PEER_LEAVE: "Peerverlof",
    HAND_RAISED: "Handen omhoog",
    ERROR: "Fout",
    TILES_IN_VIEW: "Tegels In Zicht",
    AUDIO_ONLY_MODE: "Alleen audio-modus",
    MIRROR_LOCAL_VIDEO: "Spiegel lokale video",
    SIT_BACK_AND_RELAX: "Leun achterover en ontspan totdat anderen meedoen",
    SCREEN_SHARE_CANCEL: "Gebruiker heeft geen toestemming gekregen voor toegang tot het opnameapparaat",
    START_SHARING: "Begin met delen",
    CHOOSE_WHAT_YOU_WANT_TO_SHARE: "Kies wat je wilt delen",
    SHARE_SCREEN: "Deel scherm",
    SHARE_SCREEN_SUBTITLE: "Deel uw tabblad, venster of uw hele scherm",
    SHARE_PDF: "PDF delen",
    NEW: "Nieuw",
    SHARE_PDF_SUBTITLE: "Annoteer, teken vormen en meer via PDF's",
    MORE_OPTIONS: "Meer opties",
    PARTICIPANTS: "Deelnemers",
    HAND: "Hand",
    RAISE: "Salarisverhoging",
    LOWER: "Lager",
    EMOJI_REACTIONS: "Emoji-reacties",
    POLLS_AND_QUIZZES: "Polls en quizzen",
    BE_RIGHT_BACK: "Ben zo terug",
    RECORDING_ON: "Opnemen Aan",
    STARTING_RECORDING: "Opname starten",
    START_RECORDING: "Begin met opnemen",
    ABOUT_SESSION: "Over sessie",
    ENABLE: "Inschakelen",
    DISABLE: "Uitzetten",
    PICTURE_IN_PICTURE: "Beeld-in-beeld",
    SHOW_STATS: "Toon HLS-statistieken",
    STATS_FOR_NERDS: "Statistieken voor nerds",
    POP_OUT_CHAT: "Pop-outchat",
    FULL_SCREEN: "volledig scherm",
    GO: "Gaan",
    EXIT: "Uitgang",
    SEARCH_FOR_PARTICIPANTS: "Zoek naar deelnemers",
    NO_PARTICIPANTS: "Geen deelnemers",
    NO_MATCHING_PARTICIPANTS: "Geen overeenkomende deelnemers",
    YOU: "Jij",
    CHAT: "Chat",
    HOST: "Gastheer",
    START_A_CONVERSATION: "Begin een gesprek",
    NO_MESSAGES_YET: "Nog geen berichten",
    NO_MESSAGES_YET_SUBTITLE: "Er zijn hier nog geen berichten. Begin een gesprek door een bericht te sturen.",
    SEND_A_MESSAGE: "Stuur een bericht",
    TO: "Naar",
    CHOOSE_PARTICIPANT: "Kies Deelnemer",
    EVERYONE: "Iedereen",
    PEER: "Peer",
    GUEST: "Gast",
    SEARCH: "Zoekopdracht",
    ROLES: "Rollen",
    PAUSE_CHAT: "Pauzeer het chatten",
    CHAT_PAUSED: "Chat onderbroken",
    CHAT_PAUSED_BY: "Chat is gepauzeerd door",
    RESUME: "Resume",
    BLOCKED_MESSAGE: "Je bent geblokkeerd voor het verzenden van berichten",
    POLL_AND_QUIZES: "Polls en quizzen",
    OPEN: "Open",
    CLOSE: "Dichtbij",
    POLL_TYPE: "Selecteer het type waarmee u verder wilt gaan",
    POLL: "Opiniepeiling",
    QUIZ: "Quiz",
    HIDE_VOTE_COUNT: "Stemtelling verbergen",
    ENTER_NAME: "Voer een naam in om door te gaan",
    CREATE: "Creëren",
    NAME_THIS: "Noem dit",
    PREVIOUS_POLLS_AND_QUIZZES: "Eerdere peilingen en quizzen",
    VIEW: "Weergave",
    QUESTION: "Vraag",
    OF: "van",
    QUESTION_TYPE: "Vraagtype",
    OPTIONS: "Opties",
    USE_THE_RADIO_CORRECT: "Gebruik de keuzerondjes om het juiste antwoord aan te geven",
    USE_THE_CHECK_BOX_CORRECT: "Gebruik de selectievakjes om het juiste antwoord(en) aan te geven",
    ADD_AN_OPTION: "Voeg een optie toe",
    POINT_WEIGHTAGE: "Puntgewicht",
    AT_LEAST_TWO_OPTIONS: "Er moeten minimaal twee opties worden toegevoegd",
    FILL_ALL_THE_FIELDS: "Vul alle velden in",
    MARK_CORRECT_ANSWERS: "en markeer het juiste antwoord(en)",
    TO_CONTINUE: "doorgaan",
    SAVE: "Redden",
    DELETE_QUESTION: "Vraag verwijderen",
    QUESTION_WILL_BE_DELETED: "De vraag wordt verwijderd. Je kunt deze actie niet ongedaan maken.",
    CANCEL: "Annuleren",
    DELETE: "Verwijderen",
    ADD_ANOTHER_QUESTION: "Voeg nog een vraag toe",
    LAUNCH: "Launch",
    ASK_A_QUESTION: "Stel een vraag",
    "SINGLE-CHOICE": "Enkele keuze",
    "MULTIPLE-CHOICE": "Meerkeuze",
    OPTION: "Optie",
    EDIT: "Bewerking",
    NOT_REQUIRED_TO_ANSWER: "Niet verplicht om te antwoorden",
    ANSWER: "Antwoord",
    VOTE: "Stemmen",
    STARTED_A: "begon een",
    PARTICIPANT: "Deelnemer",
    SINGLE_CHOICE: "Enkele keuze",
    MULTIPLE_CHOICE: "Meerkeuze",
    END: "Einde",
    VIEW_LEADERBOARD: "Bekijk klassement",
    ANSWERED: "Beantwoord",
    VOTED: "Gestemd",
    SKIPPED: "Overgeslagen",
    DRAFT: 'Voorlopige versie',
    LIVE: 'Live',
    ENDED: 'Beëindigd',
    VOTES: "Stemmen",
    PARTICIPATION_SUMMARY: "Deelname Samenvatting",
    CORRECT_ANSWERS: "Juiste antwoorden",
    AVG_TIME_TAKEN: "Gem. Tijd genomen",
    AVG_SCORE: "Gem. Scoren",
    YOUR_RANK: "Jouw rang",
    POINTS: "Punten",
    TIME_TAKEN: "Tijd genomen",
    YOUR_ANSWER: "Jouw antwoord",
    RAISE_HAND: "Hand opsteken",
    LOWER_HAND: "Onderhand",
    EMOGI_REACTION: "Emoji-reactie",
    START: "Begin",
    STOP: "Stop",
    SCREEN_SHARING: "scherm delen",
    SHARE: "Deel",
    VIEW_OPTIONS: "Bekijk Opties",
    OPEN_CHAT: "Chat openen",
    LEAVE_ROOM: "Verlaat de kamer",
    LEAVE_SESSION: "Sessie verlaten",
    LEAVE_STREAM: "Verlaat Stroom",
    LEAVE_SESSION_SUB_TITLE: "Anderen gaan door nadat u bent vertrokken. Je kunt lid worden van de",
    SESSION: "sessie",
    STREAM: "stroom",
    AGAIN: "opnieuw",
    END_SESSION: "Einde sessie",
    END_STREAM: "Einde stroom",
    END_SESSION_SUB_TITLE: "zal voor iedereen eindigen. Je kunt deze actie niet ongedaan maken.",
    THE: "De",
    YOU_LEFT_THE_ROOM: "Je verliet de kamer",
    HAVE_A_NICE_DAY: "Prettige dag",
    LEFT_BY_MISTAKE: "Per ongeluk achtergelaten?",
    REJOIN: "Opnieuw deelnemen",
    END_RECORDING: "Beëindig de opname",
    END_RECORDING_SUB_TITLE: "Weet u zeker dat u de opname wilt beëindigen?",
    DONT_END: "Eindig niet",
    STOP_RECORDING: "Stop met opnemen",
    STARTING: "Beginnen",
    RECORDING: "Opname",
    LEAVE: "Vertrekken",
    OTEHRS_WILL_CONTINUE: "Anderen gaan door nadat u bent vertrokken. U kunt opnieuw deelnemen aan de sessie."
};